### PR TITLE
Update the architecture of the assembly pipeline to DSL2 standards

### PR DESCRIPTION
**Pull request by mjmansfi**
Updates the pipeline to more closely match the style established in the `nf-core` [RNAseq pipeline](https://github.com/nf-core/rnaseq).

To do so requires a fairly substantial overhaul of the guts of the pipeline. Among the to-dos:

- [ ] Write Github actions for testing on PR
- [ ] Provide additional workflow-ized components of the pipeline: QC, assembly, post-assembly QC, etc.
- [ ] Provide different run modes
- [ ] Overhaul module structure to match `nf-core`
- [ ] Rewrite `nextflow_schema.json`
- [ ] Improve documentation (e.g. `oist-assemblers/docs`)
- [ ] Populate `oist-assembler/assets`
- [ ] Configure `multiQC` plots

### CODE REVIEW

**Comment by charles-plessy** [comment]
Hi Mike, here are some comments (in the order of the "Files changed" information):

 - the `assets` directory is made of empty files.  What is its purpose ?
 - `subset_fasta_by_BLAST_results.py` is not used at the moment, and I would like to propose to use `cmsearch` and `emboss` directly to extract rRNA sequences (see <https://github.com/oist/larvaceans_rRNA/blob/main/cmsearch/README.md>).
 - `conf` and `docs` are also containing only empty files
 - the files in `lib` must have a license and copyright holder(s) documented in the source tree where they come from; we need to document that in this repository's `LICENSE` file. They also contain a lot of code specific to the RNA-seq pipeline, that we would need to change later, so if they are not used yet I would suggest to wait before adding them.
 -  The `make_tree_from_BLAST_result` subworkflow does not exist in the master branch yet, so if you would like to focus on refactoring, I would suggest to leave it out for the moment.
 - Why did you remove `recurseSubmodules = true` in the `nextflow.config` file ?
 - At the moment we do not use the `check_max` function defined in the `nextflow.config` file. I propose to leave it out.

**Comment by mjmansfi** [comment]
Thank you for your comments! Here are some responses, plus a push addressing the issues.

- **Re: empty files**. I populated `assets`, `conf`, and `docs` with empty files just to establish the DSL2 directory structure. Once the pipeline is more filled out, `assets` contains things like `multiqc` templates, logos, email templates, `conf` contains various config files (mostly distinguished by test workflows I believe), and `docs` is of course documentation.
- **Re: 18S workflow.** You're right about this, these files belong on a separate branch. My intention here is to create a `gene_of_interest` workflow consisting of: 1) BLAST a query sequence 2) extract hits 3) align hits to a provided reference alignment 4) make a new tree. So `gene_of_interest` would be more flexible, but not as good for 18S as the `cmsearch` approach. We can support both.
- **Re: recurse_submodules.** No reason, actually. I can add it back. I don't even know what it does.
- **Re: check_max.** `check_max` is defined and used elsewhere within the submodules, so removing it from the top-level `nextflow.config` should be fine.

EDIT: `recurseSubmodules` raises a warning, when run with `-profile docker` at least. See attached.
Screenshot from 2021-02-10 14-39-09

**Comment by mjmansfi** [comment]
@charles-plessy Should this be merged in to `oist-assembler` as is, or should this PR be used to re-factor into the modular design we proposed?

Asking now because merging becomes more difficult as this repo diverges from the modules and your own development.

**Comment by mjmansfi** [comment]
Closing this to submit a new PR. The intention of this PR was to bring the `oist-assembler` repo up to speed with other `nf-core` modules, but it was not created with `nf-core create`, so it is missing a lot of the required files to make this `nf-core`-friendly.

My next PR will be to update `oist-assembler` to its intended role as a sandbox for creating new modules and processes for later addition to the `nf-core-denovohybrid` repo.

**Pull request closed without merging**
